# Change these first
owner: Mooncyan # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: THORN 官网 (中国)
    url: https://thorn.red
  - name: THORN 数据同步服务 (中国)
    url: https://syncpoint.thorn.red/latency
  - name: THORN Website
    url: https://www.thorn.so
  - name: THORN Data Sync Service (Asia)
    url: https://hk.syncpoint.thorn.so/latency
  - name: THORN Data Sync Service (North America)
    url: https://sv.syncpoint.thorn.so/latency

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: THORN
  theme: light
  introTitle: "**THORN** Status"
  introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here. As always, if you are experiencing any issues with THORN, don't hesitate to get in touch with us at support@thorn.so.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true


i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
  
  

